version: '3'
services:

  calibra_server:
    build: ./CalibraServer/
    container_name: CalibraServer
    volumes:
      - calibra_server_volume:/usr/src/app
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - 7070:7070

  genetic_deployer_server:
    build: ./GeneticDeployerServer/
    container_name: GeneticDeployerServer
    volumes:
      - genetic_server_volume:/usr/src/app
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - 8080:8080

  runtime_visualizer_server:
    build: ./RuntimeVisualizerServer/
    container_name: RuntimeVisualizerServer
    volumes:
      - genetic_server_volume:/usr/src/app
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - 6006:6006

volumes:
  calibra_server_volume:
  genetic_server_volume:


