name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.13'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f GeneticDeployerServer/requirements.txt ]; then pip install -r GeneticDeployerServer/requirements.txt; fi
          if [ -f GeneticDeployerServer/test-requirements.txt ]; then pip install -r GeneticDeployerServer/test-requirements.txt; fi
          if [ -f CalibraServer/requirements.txt ]; then pip install -r CalibraServer/requirements.txt; fi

      - name: Generate Codecov Report
        run: |
          coverage run --source=src -m unittest discover tests/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
